### ISSUE TITLE
Cotizacion y definion de modelos

### ISSUE THREAD

**Issue by buritica** [colombia-dev/merch#1]
- [x] cotizar orden de 50 camisetas, 1 color o varios
- [x] cotizar orden de 50 buzos, 1 color o varios

## Camiseta

![](https://vangogh.teespring.com/shirt_pic/4023852/4608862/2/2397/480x9999/front.jpg?v=2015-12-28-06-20)
![](https://vangogh.teespring.com/shirt_pic/4023852/4608862/2/2397/480x9999/back.jpg?v=2015-12-28-06-20)

## Hoodie

![](https://vangogh.teespring.com/shirt_pic/4023852/4608862/212/5819/480x9999/front.jpg?v=2015-12-28-06-20)
![](https://vangogh.teespring.com/shirt_pic/4023852/4608862/212/5819/480x9999/back.jpg?v=2015-12-28-06-20)

**Comment by mongrelion** [comment]
@buritica esto ya se llevó a producción hace muchos años. ¿Podemos cerrar esto?
